import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

/* ----IMPORTS---- */
import Button from './componentes/button';
import Card from './componentes/card';
import datos from './data/data'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Clase 10</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1> Ejercicio de la Clase 10 </h1>
        <br></br>

        <Button></Button>

        <div className='container__card'>
          {datos.map(card =>
            <Card key={card.id}
              titulo={card.titulo}
              subtitulo={card.subtitulo}
              text={card.text}
            />
          )}
        </div>
      </main>
    </>
  )
}
